### ISSUE TITLE
Not able to align json

### ISSUE THREAD

**Issue by PoloMaillardet** [adrianlee44/atom-aligner-javascript#1]
Since v1.2.0 (I believe), I'm not able to align `json` string anymore.

Nothing happens, and no error in the console. Is this "language" not supported anymore ? Is there something in the settings to change in order to work ? Or is there any package specific to `json` alignment ? Thanks !

**Comment by adrianlee44** [comment]
Thanks for flagging this. I didn't realize the change broke JSON. The latest version v1.3.0 of aligner-javascript should fix the issue.

**Comment by PoloMaillardet** [comment]
Great, many thanks! How reactive! :)

**Comment by PoloMaillardet** [comment]
I confirm that release 1.3.0 fixes the issue. Perfect! Thanks again.
